---
description: 编译器错误 CS1015
title: 编译器错误 CS1015
ms.date: 07/20/2015
f1_keywords:
- CS1015
helpviewer_keywords:
- CS1015
ms.assetid: 53179feb-e8be-41e0-bb0b-f7879e9fa613
ms.openlocfilehash: 6d7afd45846d85f64da8eab5cf9ea3b1a6db3f08
ms.sourcegitcommit: 5b475c1855b32cf78d2d1bbb4295e4c236f39464
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/24/2020
ms.locfileid: "91202638"
---
# <a name="compiler-error-cs1015"></a><span data-ttu-id="f5ef1-103">编译器错误 CS1015</span><span class="sxs-lookup"><span data-stu-id="f5ef1-103">Compiler Error CS1015</span></span>

<span data-ttu-id="f5ef1-104">应是对象、字符串或类类型</span><span class="sxs-lookup"><span data-stu-id="f5ef1-104">An object, string, or class type expected</span></span>  
  
 <span data-ttu-id="f5ef1-105">尝试将预定义的数据类型传入 [catch](../language-reference/keywords/try-catch.md) 块。</span><span class="sxs-lookup"><span data-stu-id="f5ef1-105">An attempt was made to pass a predefined data type into a [catch](../language-reference/keywords/try-catch.md) block.</span></span> <span data-ttu-id="f5ef1-106">仅派生自 <xref:System.Exception?displayProperty=nameWithType> 的数据类型可传入 `catch` 块。</span><span class="sxs-lookup"><span data-stu-id="f5ef1-106">Only data types that derive from <xref:System.Exception?displayProperty=nameWithType> can be passed into a `catch` block.</span></span> <span data-ttu-id="f5ef1-107">有关异常的详细信息，请参阅 [异常和异常处理](../programming-guide/exceptions/index.md)。</span><span class="sxs-lookup"><span data-stu-id="f5ef1-107">For more information on exceptions, see [Exceptions and Exception Handling](../programming-guide/exceptions/index.md).</span></span>  
  
## <a name="example"></a><span data-ttu-id="f5ef1-108">示例</span><span class="sxs-lookup"><span data-stu-id="f5ef1-108">Example</span></span>  

 <span data-ttu-id="f5ef1-109">下面的示例生成 CS1015：</span><span class="sxs-lookup"><span data-stu-id="f5ef1-109">The following sample generates CS1015:</span></span>  
  
```csharp  
// CS1015.cs  
class Sample  
{  
    static void Main()  
    {  
        try
        {  
        }  
        catch(int)   // CS1015, int is not derived from System.Exception  
        {  
        }  
    }  
}  
```
