---
description: 编译器错误 CS1626
title: 编译器错误 CS1626
ms.date: 07/20/2015
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
ms.openlocfilehash: ef228c64e250569a4b2af0e6705d410853d7e299
ms.sourcegitcommit: 5b475c1855b32cf78d2d1bbb4295e4c236f39464
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/24/2020
ms.locfileid: "91176508"
---
# <a name="compiler-error-cs1626"></a><span data-ttu-id="207c4-103">编译器错误 CS1626</span><span class="sxs-lookup"><span data-stu-id="207c4-103">Compiler Error CS1626</span></span>

<span data-ttu-id="207c4-104">无法在包含 catch 子句的 Try 块体中生成值</span><span class="sxs-lookup"><span data-stu-id="207c4-104">Cannot yield a value in the body of a try block with a catch clause</span></span>  
  
 <span data-ttu-id="207c4-105">如果有一个 catch 子句与 try 块关联，该 try 块内不允许有 yield 语句。</span><span class="sxs-lookup"><span data-stu-id="207c4-105">A yield statement is not allowed in a try block if there is a catch clause associated with the try block.</span></span> <span data-ttu-id="207c4-106">若要避免此错误，请将 yield 语句移出 try/catch/finally 块，或删除 catch 块。</span><span class="sxs-lookup"><span data-stu-id="207c4-106">To avoid this error, either move the yield statement out of the try/catch/finally block, or remove the catch block.</span></span>
  
 <span data-ttu-id="207c4-107">下面的示例生成 CS1626：</span><span class="sxs-lookup"><span data-stu-id="207c4-107">The following sample generates CS1626:</span></span>  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
      finally
      {

      }
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
